### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by iomari** [javascript-tutorial/en.javascript.info#2665]
╰─ ./edit en                                                                                                                                ─╯
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/iomari/git-repos/javascript.info/server/node_modules/.bin/cross-env:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by siddiqkaithodu** [comment]
You should check this out .

https://stackoverflow.com/questions/57621347/how-to-solve-this-error-internal-modules-cjs-loader-js638-throw-err
